In [1]:
import pandas as pd
import numpy as np
import ast # to make the string representation of list back to list
df = pd.read_csv("preprocessed_data.csv")
df['text'] = df['text'].apply(ast.literal_eval)

In [2]:
df['next_word'] = df['next_word'].apply(lambda x: [x])

df.head()

                            text next_word
0                            [i]    [hope]
1                      [i, hope]    [this]
2                [i, hope, this]   [email]
3         [i, hope, this, email]   [finds]
4  [i, hope, this, email, finds]     [you]

In [3]:
df.head()

                            text next_word
0                            [i]    [hope]
1                      [i, hope]    [this]
2                [i, hope, this]   [email]
3         [i, hope, this, email]   [finds]
4  [i, hope, this, email, finds]     [you]

In [4]:

max_length = df['text'].str.len().max()
index = df['text'].str.len().idxmax()
print("The longest text is:", df['text'].iloc[index])
print("The length of the longest text is:", len(df['text'].iloc[index]))
print(max_length)

The longest text is: ['your', 'commitment', 'to', 'excellence', 'sets', 'a', 'high', 'standard', 'for', 'the', "teamlet's", 'schedule', 'a', 'conference', 'call', 'to', 'discuss', 'the', 'details']
The length of the longest text is: 19
19

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23790 entries, 0 to 23789
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   text       23790 non-null  object
 1   next_word  23790 non-null  object
dtypes: object(2)
memory usage: 371.8+ KB

In [6]:
df['next_word'].str.len().max()

np.int64(1)

total words

In [7]:
all_words = set()
for text in df['text']:
    all_words.update(text)
for text in df['next_word']:
    all_words.update(text)
all_words = list(all_words)
print(len(all_words))

3037

In [8]:
all_words

['arranging',
 'company-wide',
 'surprised',
 'reinforcing',
 'morning',
 'astronomy',
 'modular',
 'grappling',
 'attend',
 'positioned',
 'overview',
 'skincare',
 'neighborhoods',
 'remotely',
 'sunset',
 'essential',
 'paper',
 'digitization',
 'taco',
 'major',
 'pride',
 'lights',
 'comes',
 'tasks',
 'precision',
 'organization',
 'next',
 'accomplishments',
 'showed',
 'address',
 'obstacles',
 'excelling',
 'execution',
 'such',
 'correlation',
 'networking',
 'measures',
 'fictional',
 'delegate',
 'researching',
 'pay',
 'received',
 'starting',
 'diversified',
 'moving',
 'events',
 'whether',
 'debriefing',
 'constantly',
 'opportunities',
 'spark',
 'mechanisms',
 'number',
 'leveraging',
 'apparent',
 'groundbreaking',
 'version',
 'future',
 'this',
 'guide',
 'fostering',
 'conservation',
 'systems',
 'dialogue',
 'weeks',
 'designated',
 'recruitment',
 'part',
 'board',
 'ask',
 'at',
 'evaluating',
 'issues',
 'satisfaction',
 'stuck',
 'reduction',
 'sent',
 'declutter',
 'champions',
 'shaped',
 'compliance',
 'prioritizing',
 'seen/read',
 'discuss',
 'hiking',
 'wondering',
 'great',
 'stress-relief',
 'partnered',
 'guitar',
 'excited',
 'levels',
 'capturing',
 'proposal',
 'heart',
 'study',
 "speaker's",
 'cost-benefit',
 'grace',
 'sum',
 'challenging',
 'tuesday',
 'specialized',
 'show',
 'holistic',
 'ethical',
 'consistently',
 'session',
 'committee',
 'getting',
 'dedicate',
 'expense',
 'establish',
 'increases',
 'consensus',
 'dedicated',
 'thumb',
 'routes',
 'perspective',
 'homebuyer',
 'comprises',
 'accomplishment',
 'listens',
 'has',
 'bottlenecks',
 'emphasizes',
 'inspired',
 "let's",
 'accordingly',
 'public',
 'literature',
 'freely',
 'favor',
 'countryside',
 'enhancements',
 'pipelines',
 'that',
 'healthier',
 'friendship',
 'craft',
 'dealings',
 'education',
 'aims',
 'assessment',
 'role',
 'ice',
 'enhancement',
 'martial',
 'integral',
 'lifestyle',
 'adding',
 'emphasized',
 'user',
 'contemplated',
 'chess',
 'specified',
 "there's",
 'workload',
 'dispensed',
 'workday',
 'first-time',
 'leverage',
 'seen',
 'lot',
 'brainstorm',
 'diet',
 'solutions',
 'motivate',
 'feels',
 'responsibly',
 'latest',
 'finished',
 'adjustments',
 'gladly',
 'undergo',
 'keeping',
 'and',
 'your',
 'reflects',
 'herb',
 'his',
 'something',
 'personalized',
 'addicting',
 'requests',
 'meeting',
 'speak',
 'retirement',
 'birdwatching',
 'fashion',
 'analyzed',
 'existing',
 'to',
 'organized',
 'misunderstandings',
 'spearheads',
 'academic',
 'communication',
 'ideas',
 'section',
 'cultural',
 'measurable',
 'attentive',
 'time',
 'seek',
 'cleanup',
 'eating',
 'targets',
 'continuing',
 'pioneer',
 'expo',
 'harmonious',
 'using',
 'reality',
 'theater',
 'explores',
 'program',
 'raised',
 'journaling',
 'directors',
 'work-life',
 'say',
 'participation',
 'admirable',
 'results-oriented',
 'side',
 'necessary',
 'park',
 'analytics',
 'prevalent',
 'responsiveness',
 'utilize',
 'stand',
 'calming',
 'modules',
 'perhaps',
 'assists',
 'installations',
 'reflected',
 'annual',
 'principles',
 'reassessing',
 'improves',
 'recipe',
 'identifying',
 'reflection',
 'meant',
 'impact',
 'submit',
 'alignment',
 'amplify',
 'anticipate',
 'sustainable',
 'filled',
 'formally',
 'onboarding',
 'effective',
 'task',
 'strolls',
 'real-time',
 'not',
 'collaboratively',
 'volatility',
 'convenient',
 'commendable',
 'capable',
 'advocates',
 'concisely',
 'listener',
 "hasn't",
 'investment',
 'podcasts',
 'community',
 'leadership',
 'forums',
 'both',
 'cup',
 'town',
 'generosity',
 'behind',
 'soon',
 'conferences',
 'digital',
 'connection',
 'staycation',
 'commute',
 'connections',
 'stakeholder',
 'presenting',
 'reports',
 'about',
 'fair',
 'alert',
 'streamlined',
 'adventurous',
 'influencers',
 'loss',
 'talk',
 'chores',
 'graciously',
 'discover',
 'scenery',
 'meticulous',
 'habit',
 'joining',
 'guidance',
 'exhibition',
 'touch',
 'instrument',
 'lie',
 'effectively',
 'solver',
 'close',
 'analysis',
 'workplace',
 'band',
 'collective',
 'conducive',
 'responsibility',
 'seamless',
 'drives',
 'love',
 'resilience',
 'permission',
 'time-management',
 'gain',
 'atm',
 'prevent',
 'resolved',
 'energized',
 'confident',
 'aspects',
 'cool',
 'banking',
 'capitalizing',
 'fellow',
 'lobbying',
 'lifelong',
 'city',
 'boost',
 'idea',
 'sponsored',
 'rescue',
 'provides',
 'professionally',
 'participated',
 'burnout',
 'aligned',
 'foreseeing',
 'summary',
 'summarize',
 'proactive',
 'depends',
 'engage',
 'unpredictable',
 'idea-sharing',
 'shows',
 'tap',
 'workshop',
 'hangout',
 'impression',
 'architecture',
 'strategizes',
 'nearby',
 'utilizes',
 'box',
 'containerization',
 'resignation',
 'reserves',
 'resulted',
 'practicing',
 'remain',
 'steps',
 'learn',
 'pizza',
 'diversification',
 'crisis',
 'shortage',
 'businesses',
 'arrangements',
 'relaxing',
 'bit',
 'drafting',
 'handled',
 'advised',
 'preferences',
 'instagram',
 'economic',
 'motivational',
 'equipped',
 "farmer's",
 'self-compassion',
 'excellent',
 'activities',
 'resourceful',
 'excel',
 'just',
 'lunch',
 'the',
 'markets',
 'beach',
 'achievable',
 'corporate',
 'gift',
 'live',
 'acquiring',
 'proofread',
 'adjusting',
 'exploring',
 'weekend',
 'quick',
 'automotive',
 'strategic',
 'positivity',
 'tirelessly',
 'streamline',
 'inspiring',
 'accomplishments;',
 'checklist',
 'nature',
 'anticipates',
 'money',
 'skill',
 'invest',
 'hit',
 'time-tracking',
 'detail-oriented',
 'incorporate',
 'highlighted',
 'thinker',
 'equipment',
 'current',
 'consistent',
 'fast-paced',
 'loyalty',
 'crm',
 'resolution',
 'high-pressure',
 'gadget',
 'list',
 'enrichment',
 'being',
 'stay',
 'maintenance',
 'set',
 'self-reflection',
 'cultivated',
 'stress',
 'thing',
 'clean-up',
 'need',
 'beliefs',
 'high',
 'social',
 'inner',
 'decor',
 'items',
 'planning',
 'exclusive',
 'focusing',
 'assesses',
 'can-do',
 'cycling',
 'competencies',
 'force',
 'forward-thinking',
 'without',
 'grievances',
 'cinematic',
 'hiring',
 'revised',
 'particular',
 'department',
 'disciplines',
 'impromptu',
 'well-deserved',
 'called',
 'scientific',
 'talents',
 'turned',
 'cartoons',
 'question',
 'conversations',
 'used',
 'acquired',
 'empowering',
 'be',
 'perusal',
 'marketing',
 'attached',
 'possess',
 'curiosity',
 'pricing',
 'deposit',
 'grab',
 'yet',
 'excellence',
 'strengthen',
 'communicator',
 'whatsapp',
 'underwent',
 'liabilities',
 'household',
 'position',
 'regulatory',
 'overseen',
 'authenticity',
 'fears',
 'them',
 'outlet',
 'happy',
 'reshaping',
 'union',
 'initiate',
 'vision',
 'museum',
 'ahead',
 'fosters',
 'exercise',
 'trending',
 'collaborated',
 'contract',
 'quotes',
 'indicates',
 'scarcity',
 'repeat',
 'employee',
 'comfort',
 'strategizing',
 'festival',
 'early',
 'encouraging',
 'deeply',
 'is',
 'interactions',
 'bottom',
 'everything',
 'mindfulness',
 'mentor',
 'driving',
 'success',
 'conflicts',
 'hear',
 'celebrating',
 'support',
 'allocation',
 'economy',
 'deep',
 'accuracy',
 'mortgage',
 'safe',
 'manager',
 'partner',
 'revisit',
 'left',
 'considering',
 'professionals',
 'solve',
 'what',
 'reassess',
 'painting',
 'path',
 'defines',
 'guess',
 'status',
 'emails',
 'shared',
 'benchmarks',
 'workflow',
 'effectiveness',
 'rather',
 'addictive',
 'bills',
 'member',
 'reflections',
 'strive',
 'form',
 'advancing',
 'restaurant',
 'order',
 "what's",
 'revolves',
 'helpline',
 'terms',
 'thrilled',
 'compassion',
 'assisting',
 'living',
 'shown',
 'loan',
 'allow',
 'demonstrates',
 'player',
 'productive',
 'career',
 'brainstorming',
 'ongoing',
 'inspiration',
 'passions',
 'advisor',
 'later',
 'anticipated',
 'loop',
 'cost-cutting',
 'up',
 'beyond;',
 'ensures',
 'main',
 'validate',
 'resonates',
 'personal',
 'gathers',
 'successfully',
 'narrative',
 'destination',
 'thursday',
 'automating',
 'range',
 'habitat',
 'other',
 'each',
 'conveying',
 'skill-building',
 'fueled',
 'channels',
 'national',
 'tree-planting',
 'culture',
 'her',
 'movies',
 'high-quality',
 'feasibility',
 'shelter',
 'silos',
 'small',
 'into',
 'suggests',
 'below',
 'hunt',
 'generated',
 'laugh',
 'arrange',
 'laughter-filled',
 'trust',
 'expressing',
 'running',
 'aim',
 'integrate',
 'demonstrating',
 'costume',
 'outcomes',
 'difference;',
 'tailored',
 'phone',
 'multiple',
 'problem;',
 'opinion',
 'adaptation',
 'circumstances',
 'express;',
 'eco-conscious',
 'exam',
 'different',
 'predict',
 'relaxation',
 'design',
 'plants',
 'care',
 'lost',
 'sidekick',
 'interactive',
 'greener',
 'flower',
 'partnerships',
 'training',
 'facilitating',
 'significant',
 'play',
 'emerging',
 'detail',
 'trivia',
 'benefit',
 'brighter',
 'enjoy',
 'congratulations',
 'celebrate',
 'language',
 'tracking',
 'off',
 "experiment's",
 'regarding',
 'hotline',
 'we',
 'caliber',
 'intrigues',
 'wealth',
 'resume',
 'insightful',
 'resolving',
 'style',
 'explained',
 'rate',
 'busy',
 'rigorous',
 'pic',
 'possesses',
 'progress',
 'encouraged',
 'inclusion',
 'renewable',
 'involvement',
 'tact',
 'result',
 'patiently',
 'competitors',
 'response',
 'participating',
 'with',
 'discussions',
 'proposed',
 'run',
 'start',
 'shot',
 'joy',
 'confidentiality',
 'compassionate',
 'flexible',
 'earliest',
 'image',
 'launches',
 'recycle',
 'problem',
 "stakeholders'",
 "nature's",
 'platform',
 'routine',
 'travel',
 'sectors',
 'individuality',
 'location',
 'engaging',
 'acknowledging',
 'operations',
 'course',
 'discovered',
 'menu',
 'blockchain',
 'might',
 'extend',
 'heard',
 'enhanced',
 'environmentally',
 'portfolio',
 'i',
 'announce',
 'panel',
 'advocate',
 'long-term',
 'communicated',
 'charity',
 'monitor',
 'attitude',
 'appreciated',
 'failure',
 'self-awareness',
 'mean',
 'tips',
 'outing',
 'stunning',
 'matter',
 'stability',
 'showcasing',
 'gone',
 'outline',
 'demonstrated',
 'valued',
 'so',
 'talented',
 'after',
 'fuels',
 'uncertainties',
 'supervisor',
 'amicably',
 'tradition',
 'age',
 'reduce',
 'greater',
 'resolutions',
 'actively',
 'own',
 'documentaries',
 'kind',
 'constructive',
 'light',
 'determined',
 'diy',
 'pressure',
 'authorization',
 'coordination',
 'language/skill',
 'party',
 'handle',
 'ceo',
 'involves',
 'staff',
 'complement',
 'expansion',
 'of',
 'responses',
 'follow',
 'hindering',
 'asset',
 'office',
 'meme',
 'freedom',
 'cognitive',
 'increase',
 'revamp',
 'getaway',
 'roadmap',
 'international',
 'finding',
 'summer',
 'communicates',
 'a',
 'renowned',
 'balances',
 'balance',
 'meetings',
 'cohesion',
 'preferred',
 'deliver',
 'encourage',
 "can't",
 'scavenger',
 'charities',
 'customers',
 'changes',
 'kickoff',
 'hackathon',
 'gesture',
 'club',
 'achievements;',
 'lessons',
 'standard',
 'efficiently',
 'detox',
 'interface',
 'are',
 'requires',
 'visionary',
 'teller',
 'achieved',
 'utilization',
 'completion',
 'immediately',
 'enough',
 'health',
 'interesting',
 'transparent',
 'thriving',
 'overcome',
 'world',
 'appropriate',
 'equally',
 'go-to',
 'storytelling',
 'deepest',
 'baking',
 'while',
 'outstanding',
 'recommendations',
 'employ',
 'acts',
 'join',
 'fresh',
 'throughout',
 'inquiry',
 'vulnerability',
 'ability',
 'practice',
 'mile',
 'avoid',
 'companion',
 'detailed',
 'clear',
 'salsa',
 'healthcare',
 'delves',
 'enclosed',
 'unforgettable',
 'nook',
 'spend',
 'investments',
 'conducts',
 'assistance;',
 'adherence',
 'acknowledge',
 'cafã©',
 'practical',
 'protocols',
 'establishing',
 'customer-focused',
 'invaluable',
 'taking',
 'investors',
 'memorable',
 'promotional',
 'considerations',
 'fundraiser',
 'payment',
 'showing',
 'week;',
 'hand',
 'offered',
 'affirmations',
 'troubleshooting',
 'all-time',
 'landscape',
 'documentary',
 'faster',
 'review',
 'help;',
 'accommodating',
 'machine',
 'navigate',
 'chaos',
 'collaborations',
 'apply',
 'negotiations',
 'keen',
 'institution',
 'smooth',
 'am',
 'implements',
 'actionable',
 'cross-functional',
 'significantly',
 'contribute',
 'in',
 'innovate',
 'traffic',
 'automated',
 'software',
 'local',
 'agreeing',
 'procedures',
 "weather's",
 'rectify',
 'thoughts',
 'reflect',
 'accommodate',
 'utilized',
 'perfect',
 'pottery',
 'deal',
 'streamlining',
 'abundance',
 'possibilities',
 'tunes',
 'scenic',
 'report',
 "how's",
 'reminded',
 'executive',
 'bonds',
 'branch',
 'yoga"',
 'refurbish',
 'strength',
 'blessing',
 'alliances',
 'adaptable',
 'concert',
 'transition',
 'acting',
 'cost',
 'nurturing',
 'efforts',
 'diligently',
 'cute',
 'inclusive',
 'relax',
 'industry',
 'comforting',
 'more',
 'classic',
 'amazing',
 'diversifying',
 'mindful',
 'encryption',
 'profitability',
 'friendly',
 'bakery',
 'attending',
 'negotiated',
 "you've",
 'embark',
 'withdrawal',
 'skillset',
 ...]

In [9]:
all_words.index('charismatic')

1221

In [10]:
id = {word: idx+1 for idx, word in enumerate(all_words)}  # idx +1 because we want to reserve 0 for padding
print(id['charismatic'],id['impose'])

1222 2302

In [11]:
word_id = {idx: word for word, idx in id.items()}
print(word_id[1], word_id[22])

arranging lights

In [12]:
x  = pd.Series(df['text'].apply(lambda text: [id[word] for word in text]))
y = pd.Series(df['next_word'].apply(lambda text: [id[word] for word in text]))
print(x[45])
print(y[45])

[754, 1913, 193, 810, 605, 2026, 2474]
[2957]

In [13]:
print(x.shape)
print(y.shape)

(23790,)
(23790,)

In [14]:
print(x.str.len().max())
print(y.str.len().max())

19
1

In [15]:
df=pd.DataFrame({'text': x, 'next_word': y})
df.head()

                          text next_word
0                        [754]    [1106]
1                  [754, 1106]      [59]
2              [754, 1106, 59]    [2980]
3        [754, 1106, 59, 2980]    [2952]
4  [754, 1106, 59, 2980, 2952]    [1916]

In [16]:
max_len = df["text"].str.len().max()
df['text'] = df['text'].apply(lambda x: [0]*(max_len - len(x))+x)  # padding with 0
print(df['text'][45])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 754, 1913, 193, 810, 605, 2026, 2474]

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23790 entries, 0 to 23789
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   text       23790 non-null  object
 1   next_word  23790 non-null  object
dtypes: object(2)
memory usage: 371.8+ KB

In [18]:
df.to_csv("final_data.csv", index=False)

In [19]:
import json
with open('word_to_id.json', 'w') as f:
    json.dump(id, f)
with open('id_to_word.json', 'w') as f:
    json.dump(word_id, f)

In [20]:
type(x)

pandas.Series